CREATE DATABASE IF NOT EXISTS giftbaby;
USE giftbaby;

CREATE TABLE  IF NOT EXISTS Admin (
	id VARCHAR(1) PRIMARY KEY NOT NULL,
	nome VARCHAR(42) NOT NULL,
	endereco VARCHAR(42) NOT NULL,
	email VARCHAR(42) NOT NULL,
	telefone VARCHAR(20) NOT NULL ,
	senha VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Produtos (
	idPublicacao INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nomeProduto VARCHAR(42) NOT NULL,
	tamanho DOUBLE NOT NULL,
	preco DOUBLE NOT NULL,
	descricao VARCHAR(100) NOT NULL,
	foto longblob NOT NULL
);